DROP TABLE IF EXISTS NGOs;
CREATE TABLE NGOs (
EIN INT(50) NOT NULL,
NGOName VARCHAR(100) NOT NULL,
ICO VARCHAR(100),
NGOStreet VARCHAR(100),
ZIP9 VARCHAR(100),
NGOGroup VARCHAR(100),
Subsection VARCHAR(100),
Affliation VARCHAR(100),
Classification VARCHAR(100),
Ruling VARCHAR(100),
Deductibility VARCHAR(100),
Foundation VARCHAR(100),
Activity VARCHAR(100),
Organization VARCHAR(100),
NGOStatus VARCHAR(100),
TaxPeriod VARCHAR(100),
AssetCode VARCHAR(100),
IncomeCode VARCHAR(100),
FilingCode VARCHAR(100),
PF VARCHAR(100),
AccountingPeriod VARCHAR(100),
Asset Decimal(20,2),
Income Decimal(20,2),
Revenue Decimal(20,2),
NTEE VARCHAR(10),
SortName VARCHAR(100),
PRIMARY KEY (EIN));

DROP TABLE IF EXISTS ZIPs;
CREATE TABLE ZIPs (
ZIP5 INT(50) NOT NULL,
State VARCHAR(100),
MSA1 VARCHAR(100),
MSA2 VARCHAR(100),
MSA3 VARCHAR(100),
PRIMARY KEY (ZIP5));

DROP TABLE IF EXISTS Has;
CREATE TABLE Has (
EIN INT(50),
ZIP5 INT(50) NOT NULL,
PRIMARY KEY (EIN,ZIP5),
FOREIGN KEY (EIN) REFERENCES NGOs(EIN),
FOREIGN KEY (ZIP5) REFERENCES ZIPs(ZIP5));

DROP TABLE IF EXISTS Sections;
CREATE TABLE Sections (
Section VARCHAR(200) NOT NULL,
Description VARCHAR(500),
Nature VARCHAR(200),
AppForm VARCHAR(200),
AnnualForm VARCHAR(200),
Contributions VARCHAR(200),
PRIMARY KEY (Section));

CREATE INDEX Subsection_id ON NGOs (Subsection);

DROP TABLE IF EXISTS BelongsTo;
CREATE TABLE BelongsTo (
Subsection VARCHAR(100),
Section VARCHAR(200) NOT NULL, 
FOREIGN KEY (Subsection) REFERENCES NGOs(Subsection),
FOREIGN KEY (Section) REFERENCES Sections(Section));


DROP TABLE IF EXISTS RatedNGOs;
CREATE TABLE RatedNGOs (
EIN INT(50) NOT NULL,
Overall DECIMAL(5,2),
Financial DECIMAL(5,2),
Transparency DECIMAL(5,2),
Tel VARCHAR(100),
Website VARCHAR(200),
FOREIGN KEY (EIN) REFERENCES NGOs(EIN));


DROP TABLE IF EXISTS Missions;
CREATE TABLE Missions (
EIN INT(50) NOT NULL, 
Missions VARCHAR(5000),
WordsCount VARCHAR(200), 
FOREIGN KEY (EIN) REFERENCES NGOs(EIN));

DROP TABLE IF EXISTS Programs;
CREATE TABLE Programs (
EIN INT(50) NOT NULL,
Program VARCHAR(500),
Expense VARCHAR(200), 
ExpenseRate VARCHAR(200),
PRIMARY KEY (Program),
FOREIGN KEY (EIN) REFERENCES NGOs(EIN));

