LOAD DATA LOCAL INFILE 'E:/NGOdatabase/NGOs1.csv' 
INTO TABLE yuxiaoDB.NGOs 
FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'E:/NGOdatabase/ZIPs1.csv' 
INTO TABLE yuxiaoDB.ZIPs 
FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'E:/NGOdatabase/Has1.csv' 
INTO TABLE yuxiaoDB.Has 
FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'E:/NGOdatabase/Sections1.csv' 
INTO TABLE yuxiaoDB.Sections 
FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
LINES TERMINATED BY '\r\n';

LOAD DATA LOCAL INFILE 'E:/NGOdatabase/BelongsTo1.csv' 
INTO TABLE yuxiaoDB.BelongsTo 
FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
LINES TERMINATED BY '\r\n';

LOAD DATA LOCAL INFILE 'E:/NGOdatabase/RatedNGOs1.csv' 
INTO TABLE yuxiaoDB.RatedNGOs 
FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'E:/NGOdatabase/Missions1.csv' 
INTO TABLE yuxiaoDB.Missions 
FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
LINES TERMINATED BY '\r\n';

LOAD DATA LOCAL INFILE 'E:/NGOdatabase/Programs1.csv' 
INTO TABLE yuxiaoDB.Programs 
FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
LINES TERMINATED BY '\r\n';





